---
- name: Perform optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Configure local hostnames
  ansible.builtin.include_tasks: hosts.yml

- name: Configure vmail user
  ansible.builtin.include_tasks: user.yml

- name: Configure mariadb
  ansible.builtin.include_tasks: mariadb.yml
